### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by WakeUp911** [niceboygithub/AqaraCameraHubfw#1]
Hello, write, please, manual how flash this firmware. Thanks.

**Comment by niceboygithub** [comment]
Currently, no method to flash.
Can not find firmware which can flash by uboot.
The raw firmwares in this repo was dumped by dd.
The ota update bin can be used to update by "/etc/ota.sh". The ota bin is put in SDCARD (/mnt/sdcard/ota.bin).
