### ISSUE TITLE
How to update G3 firmware in telnet

### ISSUE THREAD

**Issue by glaypeng78** [niceboygithub/AqaraCameraHubfw#11]
Thanks for your nice work. I was successfully go through the step from [Wh1terat/aQRootG3](https://github.com/Wh1terat/aQRootG3) and use your code to make my G3 intergrate into Home Assistant. Recently my Aqara Home app shows that there's a update to 3.3.9_0011.0004 and I mentioned that it dose not able to turn on telnet and mqtt at this version anymore. However my G3 is in  3.3.2 version and is there any way to manually update from 3.3.2 to 3.3.4 by the stock firmware that you provide here? I have tried the way that you provide for other Aqara device but it didn't work. Could you help me to take a look at my processes?

#cd /tmp && wget -O /tmp/curl "http://master.dl.sourceforge.net/project/aqarahub/binutils/curl?viasf=1" && chmod a+x /tmp/curl
#/tmp/curl -s -k -L -o /tmp/G3_update.bin https://raw.githubusercontent.com/niceboygithub/AqaraCameraHubfw/main/stock/G3/20211216200913_lumi.camera.gwpagl01_AIOT_V3.3.4_0007.0004_20211216_28f9c3.bin
#fw_upgrade /tmp/G3_update.bin

After I use these code it show this result.
[https://i.imgur.com/T17nUVO.jpg](https://i.imgur.com/T17nUVO.jpg)

**Comment by niceboygithub** [comment]
You use the wrong method.
Please do not create your own method if you don't understand G3.
