### ISSUE TITLE
Cannot connect to G2H telnet

### ISSUE THREAD

**Issue by a000a498** [niceboygithub/AqaraCameraHubfw#13]
When my UART is plugged into the computer, the camera doesn't respond, neither does the telnet
please help me to see where I am doing wrong
![IMG_0528](https://user-images.githubusercontent.com/33992911/178799888-372004cf-d1f6-4716-9e1d-f8eb5ccd18f3.JPG)
![IMG_0529](https://user-images.githubusercontent.com/33992911/178799924-41fd19fb-5d1d-448f-a328-eb23a836ac86.JPG)
![IMG_0527](https://user-images.githubusercontent.com/33992911/178799950-4c824305-9aaa-40b0-aced-2bcd2784182f.JPG)

**Comment by niceboygithub** [comment]
You need swap RX and TX, Also do not connect 5V from pcb.
Use USB power cable to power up G2H.

**Comment by a000a498** [comment]
> You need swap RX and TX, Also do not connect 5V from pcb.
> 
> Use USB power cable to power up G2H.

So GND still connect right?

**Comment by a000a498** [comment]
![image](https://user-images.githubusercontent.com/33992911/178907062-77764775-1792-43dc-88f8-28f7689b9952.png)
![IMG_0531](https://user-images.githubusercontent.com/33992911/178907446-ca5589ae-0772-4fe2-ad3b-57ea647e6d5b.JPG)
I swapd RX and TX and remove 5V cable also use USB cable to power up then still cannot connect :(

**Comment by a000a498** [comment]
Update, I have successfully connected but the root account and password I entered are incorrect

**Comment by baobaobuku1210** [comment]
Why can't I enter the user name and password
<img width="757" alt="QQ20220728-220233@2x" src="https://user-images.githubusercontent.com/32222319/181525297-ad4638b2-eb12-4c0b-a7f7-14d4e84e8ab0.png">

**Comment by a000a498** [comment]
I open telnet now,but why i can not connect to aqara home :(
before i had plug sd card in to camera then it cannot connect to app

![9A1D8C23-3451-4BB7-862D-F4135CB2A3D8](https://user-images.githubusercontent.com/33992911/181880479-0292602d-6028-4e26-b1d8-feb1afca20d0.png)
![F1441C56-EB31-4E25-974E-6117E7884BFF](https://user-images.githubusercontent.com/33992911/181880482-e0de4379-c3d7-432a-9726-692985b92d1d.png)

**Comment by baobaobuku1210** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by baobaobuku1210** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by redelva** [comment]
<img width="359" alt="image" src="https://github.com/niceboygithub/AqaraCameraHubfw/assets/6871019/470a6cb4-6d3a-471c-88fe-4c11fab60ac6">

when enter screen /dev/cu.xxxx 115200

it enter screen and no output, what should i do now?

**Comment by baobaobuku1210** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
