### ISSUE TITLE
RTSP script autoload not working

### ISSUE THREAD

**Issue by NeroWard** [niceboygithub/AqaraCameraHubfw#14]
I was able to run the RTSP server in high quality on G2 firmware 3.5.8_0062, but there was a problem with RTSP starting automatically. If you try to manually run the rtsp-start.sh script, the telnet command line hangs, only rebooting the camera helps. Question: how to force the rtsp server to start?

What I've done:
1. Got access to UART to start Telnet
2. Copied h264grabber, rRTSPServer files to /system/bin
3. Run the "h264grabber -f &"  "rRTSPServer -e &" commands to start the RTSP stream.

Copying the rtsp_start.sh file to /system/bin, adding the contents of the rtsp_start.sh file to /etc/init.d/S90app did not autostart
 P/S sorry for my english

**Comment by niceboygithub** [comment]
The size of memory in G2 is too small.
It causes rtsp can’t run with other processes.

**Comment by NeroWard** [comment]
I ran rtsp manually, telnet worked and g2 responded to commands

**Comment by NeroWard** [comment]
There is also a display issue. Possible solutions?
In Home Assistant, the stream is received but with similar problems, there are still problems with playing the video stream in Home Assistant
![Снимок экрана (458)](https://user-images.githubusercontent.com/67514367/183894304-27affb18-6934-42eb-9b4f-fd85e847b023.png)

**Comment by NeroWard** [comment]
The image "blinks" and a normal image appears for a while, artifacts appear later

**Comment by GeorgyBenelli** [comment]
> The image "blinks" and a normal image appears for a while, artifacts appear later

I have the same problem. Did you solve the video quality problem?

**Comment by NeroWard** [comment]
> > The image "blinks" and a normal image appears for a while, artifacts appear later
> 
> I have the same problem. Did you solve the video quality problem?
I deleted the "Log" folder on the SD drive, it didn't help at all, and then it stopped helping to fix the problem at all

**Comment by creampenne** [comment]
Did you solve the problem?

**Comment by NeroWard** [comment]
> Did you solve the problem?

No, the problem has not been resolved. A bug occurs and I don't know what to do about it
