### ISSUE TITLE
RTSP stream protection

### ISSUE THREAD

**Issue by NeroWard** [niceboygithub/AqaraCameraHubfw#16]
Is it possible to create a login and password to protect an RTSP stream?How can I do that?

**Comment by niceboygithub** [comment]
Do you mean telnet login or rtsp password?

To change login password, you use the below command to change password after telnet to.
```
passwd
```

To change password of rtsp stream, you can use the below command but the username and password are dynamic.
```
killall rtsp; rtsp -a
```

**Comment by NeroWard** [comment]
I mean the RTSP password. Another question, how to find out the RTSP login and password using the command? Is it possible to make a static RTSP login and password?

**Comment by niceboygithub** [comment]
As I know, it uses dynamic login/password and can not change the usage.

to get login/password.
```
agetprop sys.camera_rtsp_url
```

**Comment by NeroWard** [comment]
Doesn't work, says command not found. Could you update rRTSPServer to the latest version of the hack
yi-hack-MStar?

**Comment by niceboygithub** [comment]
Above command are for Aqara Camera G3

What is your camera model?

**Comment by NeroWard** [comment]
G2
