### ISSUE TITLE
Help with FW modification for Aqara camera g3

### ISSUE THREAD

**Issue by T-REX-XP** [niceboygithub/AqaraCameraHubfw#20]
Hi. Can you help me to modify the latest fw for g3 cam? It's possible to share the instruction on that action?
Thanks.

**Comment by niceboygithub** [comment]
It is possible but not good time now.

**Comment by T-REX-XP** [comment]
Hi. Any updates regarding that issue?

**Comment by sdavides** [comment]
the same for me, any news?
