### ISSUE TITLE
Enable Telnet of Aqara Gateway M2 2022 link fail

### ISSUE THREAD

**Issue by tomtzeng** [niceboygithub/AqaraCameraHubfw#23]
Hi 
I found the this link:[linux.bin and rootfs.bin](https://github.com/niceboygithub/AqaraCameraHubfw/tree/main/modified/M2_2022)is no longer valid. where can I download these two files?

**Comment by niceboygithub** [comment]
Because they are not released because M3 will be released soon.

**Comment by tomtzeng** [comment]
What impact do release files from M2 POE have on the upcoming release of M3?

**Comment by niceboygithub** [comment]
M3 may use the same design. In order to use the similar method to enable telnet on M3, and providing lumi patch the issue, I need keep this method unpublished 
.

**Comment by niceboygithub** [comment]
> Hi, I'd like to know if there is a complex but working method for now. @niceboygithub 

Yes

**Comment by ashottonoyan** [comment]
https://forum.automata.id/t/topic/542

**Comment by kindansljd** [comment]
> M3 may use the same design. In order to use the similar method to enable telnet on M3, and providing lumi patch the issue, I need keep this method unpublished .

If i want to flash my M2 2022 recently,  is there any secret way to get both linux.bin and rootfs.bin? 
Or I should keep waiting until M3 been released?

**Comment by niceboygithub** [comment]
There will be two gateways, M3 and another model, both of them may use the same method to update firmware in uboot.
In case of lumi change the method, I prefer to wait for a little while to release.

**Comment by flyou** [comment]
waitting  for m2 2022 firmware

**Comment by ashottonoyan** [comment]
M3 is out https://www.aqara.cn/Hub-m3_overview
