### ISSUE TITLE
how modify roofs.bin?

### ISSUE THREAD

**Issue by sdavides** [niceboygithub/AqaraCameraHubfw#24]
Hi, can you explain to me how to change the firmware?
how modify roofs.bin?

I would like to modify last firmware aqara g3:
https://cdn.aqara.com/cdn/opencloud-product/mainland/product-firmware/prd/lumi.camera.gwpgl1/20231030143851_lumi.camera.gwpgl1_AIOT_V4.0.6_0011.0004_20231027_6b956f.bin

I tried with binwalk and unsquashfs without success.

Thanks

**Comment by niceboygithub** [comment]
The rootfs is created as squashfs, but it is signed.
The official boot sequence of G3 use signed rootfs. If not signed rootfs, it will boot failed.

**Comment by sdavides** [comment]
thanks for the reply, can you explain how to do it?  I will publish the new updated version with hack of the g3 camera tested

**Comment by sdavides** [comment]
I'm just missing the signature, could you help me?

Official rootfs.bin:
~ # /bin/fw_upgrade /mnt/sdcard/rootfs.bin
image magic:fwss, signature:lmrt, crc32:1922183475, len:25792768

My rootfs.bin:
/bin/fw_upgrade /mnt/sdcard/firmware.img
image magic:ºÁ¶X, signature:¸Qaz, crc32:998604687, len:1208766611
Error:image header magic is not fixed!fwcs, ºÁ¶X!
fw_upgrade error:-2

thanks

**Comment by niceboygithub** [comment]
As I said, the firmware of G3 is signed rootfs. Only lumi have key to sign rootfs.

**Comment by sdavides** [comment]
OK sorry, so it's not possible? 
As you did for the ones you modified here:
https://github.com/niceboygithub/AqaraCameraHubfw/tree/main/modified
?

**Comment by niceboygithub** [comment]
E1 and M2 PoE do not use signed rootfs.

**Comment by sdavides** [comment]
OK thankyou !!

**Comment by sdavides** [comment]
I saw that you are making the modified g3 firmware, good job! If you like, can you tell me how you did it for signing the .bin?
