### ISSUE TITLE
Aqara G2HPro Telnet connection refused

### ISSUE THREAD

**Issue by wizardofozzie** [niceboygithub/AqaraCameraHubfw#27]
Hey @niceboygithub - big thanks for sharing your knowledge and hustle here with us!

I downgraded the firmware on my G2H Pro to 3.3.x using the SD card booth method discussed somewhere (custom firmware, bin 7-zip extraction).

Aqara app confirms firmware version is 3.x (not 4.1.x which it was previously).

telnet connection is refused however- is this an error because I downgraded the firmware? Or is it because I'm not using Putty (i'm using macos telnet).

Thanks man, I bought you a coffee ☕️.

**Comment by wizardofozzie** [comment]
> After downgrade, you need to use aQRootG3 to enable telnet.
> 
> https://github.com/Wh1terat/aQRootG3

I'm almost there @niceboygithub 

The telnet puts me at a login screen following Wh1terat method above


```
❯ telnet 192.168.1.101
Trying 192.168.1.101...
Connected to 192.168.1.101.
Escape character is '^]'.
Camera-Hub-G2HPro-5114 login:
```


When I did this with the G3 it showed `#`. Is there a login or do I need to redo the SD hostname boot or whiterat QR code?

**Comment by niceboygithub** [comment]
If you did not make any wrong while using aGRoot3, the password of login had been removed. You can use 'root' and empty password to login.
