### ISSUE TITLE
Aqara G2 change region

### ISSUE THREAD

**Issue by rayman18** [niceboygithub/AqaraCameraHubfw#28]
Hello,

i have a Chinese G2 which only works with xiaomi home China mainland region, I can’t add it to aqara app or apple HomeKit .

Is it possible to change region in firmware or change firmware to be able to add to homekit or aqara app? Im using it from Europe. Or probably flash G2H firmware?

The current firmware is: 3.5.8_0062.0356

**Comment by niceboygithub** [comment]
No.
