### ISSUE TITLE
Help with telnet

### ISSUE THREAD

**Issue by ostgardh** [niceboygithub/AqaraCameraHubfw#5]
I have try to "create a file 'hostname' which its content as below and put it in sdcard" part
And is not working.

I try to telnet to ip and is not respond.

**Comment by niceboygithub** [comment]
What is your version of Aqara Camera?
What is the content of your hostname?

Please save the file 'hostname' as Unix type. You can use Notepad++ to save it.

**Comment by ostgardh** [comment]
hostname file.
#!/bin/sh
passwd -d root
echo WITH_TELNET=y >> /etc/.config




Version : ![image](https://user-images.githubusercontent.com/30891357/129143101-e191566f-13f7-4084-a82c-e4651b934e51.png)

Have try different sdcard 
Have try to chmod the host file to 777

**Comment by niceboygithub** [comment]
can you upload the hostname file as attachment

another solution, try [g2h-camera-mods](https://github.com/mcchas/g2h-camera-mods)

**Comment by ostgardh** [comment]
[hostname.txt](https://github.com/niceboygithub/AqaraCameraHubfw/files/6986095/hostname.txt)
I have to rename hostname file to hostname.txt

**Comment by niceboygithub** [comment]
What is the sdcard format? Is it FAT32?

How do you use telnet? Are your pc and  G2H use the same domain?

**Comment by ostgardh** [comment]
Yes. Fat32
Format by camera. 

Have try from my Debian and from putty on windows. 

Same WiFi net yes. 
Possibel to ping. 


I have noticed that the hostname file is deleted after is have be in camera.

**Comment by eneagiuseppe** [comment]
Hi @niceboygithub I really appreciated the guide, but I tried to write the hostname (unix format) inside the sdcard (formatted FAT32 or ext4) but it doesn't work. I have last firmware 2.2.3.0001.0526. Can you support us, if is it possible?
Thanks.

**Comment by niceboygithub** [comment]
The hostname way still work in 2.2.3

**Comment by the-gray-ghost** [comment]
I'm having the same problem with 2.2.3.  Tried two different SDcards Fat32 format.  File saved as 'hostname' no extension in Unix format with Notepad++.  I am using Terminal on Mac to test 'ssh root@192.168.0.113'

ssh: connect to host 192.168.0.113 port 22: Connection refused

**Comment by niceboygithub** [comment]
not ssh, please use telnet

**Comment by ostgardh** [comment]
@the-gray-ghost
Have you test telnet?
I have upgrade to 2.2.3.

Put hostname file to sdcard with the code.
Same I can´t telnet.



`Trying 192.168.0.160...
telnet: Unable to connect to remote host: Connection refused
# telnet 192.168.0.160
Trying 192.168.0.160...
telnet: Unable to connect to remote host: Connection refused
`

**Comment by jellejans** [comment]
@niceboygithub 
@ostgardh 

Is the telnet method still working with 2.2.5 ? because I tried everything, but no luck ?

**Comment by Kimbo01** [comment]
would this method works with g2h pro? I tried many times never had any success

**Comment by MostHated** [comment]
I have a g2h pro as well and have not had any success. Firmware version is 3.4.0_0008.0004

**Comment by niceboygithub** [comment]
The g2h pro did not use hostname method.
G2H pro use [aQRootG3 method](https://github.com/Wh1terat/aQRootG3), but it was invalid in 3.4.0.

**Comment by isra60** [comment]
I have v2.2.6 firmware version and it seems that telnet is not getting up. Maybe Aqara has removed it in that version? The model is G2H.

The other method xiaomi mi home soft_hack. Is there any tutorial ?
