### ISSUE TITLE
Is it possible to downgrade the Aqara GH2 HUB with your files here?

### ISSUE THREAD

**Issue by stelin66** [niceboygithub/AqaraCameraHubfw#6]
Is this orginal ota files for Aqara GH2 in this folder 
AqaraCameraHubfw/original/G2H/2.2.0.0001.0515_ota/

can i use it to restore/downgrade  if i put it on "sdcard/ota.bin

what is meant by this text "The folder refactor and add Aqara Hub E1 firmware"

**Comment by niceboygithub** [comment]
you can upgrade via ota.bin by manually enter command 
downgrade is not recommend.
